### ISSUE TITLE
For CSV source incremental delete+insert fails

### ISSUE THREAD

**Issue by Kriel** [bruin-data/ingestr#22]
I get the error:

```"AttributeError: 'NoneType' object has no attribute 'primary_key'"```

When running the command:

```
ingestr ingest --yes --source-uri "csv://all-stocks.csv" --source-table "ignored" --dest-table market.tickers --dest-uri $connectionString --incremental-strategy "delete+insert" --incremental-key "symbol" --primary-key "symbol"
```

The Append strategy seems to work fine.

Here is the full stack trace:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Scripts\ingestr.exe\__main__.py", line 7, in <module>
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\ingestr\main.py", line 465, in main
    app()
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 326, in __call__
    raise e
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 723, in main
    return _main(
           ^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ijida\AppData\Local\Programs\Python\Python312\Lib\site-packages\ingestr\main.py", line 299, in ingest
    dlt_source.incremental.primary_key = ()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'primary_key'
```

**Comment by karakanb** [comment]
this is fixed by v0.6.1 and covered with additional tests, let me know if you still experience the problem, feel free to re-open the issue if so.
